first test
KoltsovaIA/java-explore-with-me pull request #1
Opened 2023-11-18 13:00 UTC by KoltsovaIA

2023-11-19 09:55 UTC, Frilock requested changes
Добрый день, ряд небольших комментариев

2023-11-19 09:55 UTC, Frilock commented on docker-compose.yml
> +#  ewm-db:
Нужно исправить:
Закоментированный код не нужно оставлять - уберите его

2023-11-19 09:55 UTC, Frilock commented on pom.xml
> +		<module>utils</module>
Нужно исправить:
У меня отображается кривое форматирование - поправьте его

2023-11-19 09:55 UTC, Frilock commented on pom.xml
> +	<dependencyManagement>
молодцы

2023-11-19 09:55 UTC, Frilock commented on statistic/client/src/main/resources/application.properties
> +#logging.level.org.springframework.orm.jpa=INFO
Нужно исправить:
нужно убрать закоментированный код

2023-11-19 09:55 UTC, Frilock commented on statistic/server/src/main/java/ru/practicum/repository/StatRepository.java
> +            "h.app, " +
Что то вы уж совсем разбили на много строк запрос

2023-11-19 09:55 UTC, Frilock commented on statistic/server/src/main/resources/schema.sql
> +    app       VARCHAR(512)                            NOT NULL,
Нужно исправить:
Данные размеры которые вы указаываете тут, так же указывайте в аннотации Column в классе модели

2023-11-19 10:10 UTC, KoltsovaIA commented on statistic/server/src/main/resources/schema.sql
> +    app       VARCHAR(512)                            NOT NULL,
done

2023-11-19 10:15 UTC, KoltsovaIA commented on pom.xml
> +		<module>utils</module>
на github действительно выглядит криво, локально все выравнено

2023-11-19 10:16 UTC, KoltsovaIA commented on pom.xml
> +	<dependencyManagement>
спасибо

2023-11-19 10:16 UTC, KoltsovaIA commented on statistic/client/src/main/resources/application.properties
> +#logging.level.org.springframework.orm.jpa=INFO
done

2023-11-19 10:19 UTC, KoltsovaIA commented on statistic/server/src/main/java/ru/practicum/repository/StatRepository.java
> +            "h.app, " +
done

2023-11-20 18:31 UTC, Frilock approved these changes
Принято

2023-11-25 07:52 UTC, merged